from agent.cli.app import (
    ACTIVE_SSH_SESSION,
    ask_model_for_skill,
    build_parser,
    close_active_ssh_session,
    complete_interactive_input,
    execute_skill,
    explain_skill_result,
    format_session_status_with_memory,
    get_client,
    get_genai_modules,
    get_interactive_completion_candidates,
    main,
    maybe_complete_ssh_args,
    maybe_retry_ssh_with_password,
    maybe_run_cisco_playbook,
    run_agent,
    run_simulator_ssh_diagnostic,
    scan_host_tcp_ports,
)
from agent.cli.formatting import (
    build_interactive_prompt,
    format_active_session_status,
    format_help_response,
    format_identity_response,
    format_playbook_result,
    format_result_for_fallback,
    format_scan_memory,
)
from agent.cli.history import get_history_file, save_interactive_history, setup_interactive_history
from agent.cli.parsing import (
    extract_explicit_ssh_command,
    extract_json,
    is_session_info_request,
    is_casual_greeting,
    is_help_request,
    is_identity_request,
    is_scan_memory_request,
    normalize_skill_call,
    parse_direct_skill_request,
)
from agent.cli.status import get_skill_status_message, run_with_status

__all__ = [
    "ACTIVE_SSH_SESSION",
    "ask_model_for_skill",
    "build_interactive_prompt",
    "build_parser",
    "close_active_ssh_session",
    "complete_interactive_input",
    "execute_skill",
    "explain_skill_result",
    "extract_explicit_ssh_command",
    "extract_json",
    "format_active_session_status",
    "format_help_response",
    "format_identity_response",
    "format_playbook_result",
    "format_result_for_fallback",
    "format_scan_memory",
    "format_session_status_with_memory",
    "get_interactive_completion_candidates",
    "get_client",
    "get_genai_modules",
    "get_history_file",
    "get_skill_status_message",
    "is_casual_greeting",
    "is_help_request",
    "is_identity_request",
    "is_scan_memory_request",
    "is_session_info_request",
    "main",
    "maybe_complete_ssh_args",
    "maybe_retry_ssh_with_password",
    "maybe_run_cisco_playbook",
    "normalize_skill_call",
    "parse_direct_skill_request",
    "run_agent",
    "run_simulator_ssh_diagnostic",
    "scan_host_tcp_ports",
    "run_with_status",
    "save_interactive_history",
    "setup_interactive_history",
]

if __name__ == "__main__":
    main()
